version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Tu accèdes au frontend via http://localhost:3000
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"  # Tu accèdes au backend via http://localhost:8000
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: examotheque
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: examotheque
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  # script SQL à l'init (optionnel)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  # phpMyAdmin accessible via http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db

volumes:
  mysqldata:
